version: '3.7'

services:
  minecraft:
    image: ghcr.io/klauke-enterprises/paperspigot:1.19
    container_name: minecraft
    stdin_open: true
    tty: true
    restart: always
    networks:
      - minecraft
    ports:
      - 25565:25565
    volumes:
      - minecraft-data:/opt/minecraft/data

volumes:
  minecraft-data: {}

networks:
  minecraft: {}
