version: '3.7'

services:
  paper:
    image: ghcr.io/klauke-enterprises/paper:1.19
    container_name: paper
    stdin_open: true
    tty: true
    restart: always
    networks:
      - minecraft
    ports:
      - 25565:25565
    volumes:
      - paper-data:/opt/minecraft/data

volumes:
  paper-data: {}

networks:
  minecraft: {}
