name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          build-args: | 
            PAPER_VERSION=${{ matrix.version.version }}
            BUILD_VERSION=${{ matrix.version.build }}
            DOWNLOAD_VERSION=${{ matrix.version.download }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ format('{0}/{1}:{2}-{3}', env.REGISTRY, env.IMAGE_NAME, matrix.version.version, steps.meta.outputs.version) }}
    strategy:
      matrix:
        version:
          - {version: 1.8.8, build: 445, download: 'paper-1.8.8-445.jar'}
          - {version: 1.9.4, build: 775, download: 'paper-1.9.4-775.jar'}
          - {version: 1.10.2, build: 918, download: 'paper-1.10.2-918.jar'}
          - {version: 1.11.2, build: 1106, download: 'paper-1.11.2-1106.jar'}
          - {version: 1.12, build: 1169, download: 'paper-1.12-1169.jar'}
          - {version: 1.12.1, build: 1204, download: 'paper-1.12.1-1204.jar'}
          - {version: 1.12.2, build: 1620, download: 'paper-1.12.2-1620.jar'}
          - {version: 1.13-pre7, build: 12, download: 'paper-1.13-pre7-12.jar'}
          - {version: 1.13, build: 173, download: 'paper-1.13-173.jar'}
          - {version: 1.13.1, build: 386, download: 'paper-1.13.1-386.jar'}
          - {version: 1.13.2, build: 657, download: 'paper-1.13.2-657.jar'}
          - {version: 1.14, build: 17, download: 'paper-1.14-17.jar'}
          - {version: 1.14.1, build: 50, download: 'paper-1.14.1-50.jar'}
          - {version: 1.14.2, build: 107, download: 'paper-1.14.2-107.jar'}
          - {version: 1.14.3, build: 134, download: 'paper-1.14.3-134.jar'}
          - {version: 1.14.4, build: 245, download: 'paper-1.14.4-245.jar'}
          - {version: 1.15, build: 21, download: 'paper-1.15-21.jar'}
          - {version: 1.15.1, build: 62, download: 'paper-1.15.1-62.jar'}
          - {version: 1.15.2, build: 393, download: 'paper-1.15.2-393.jar'}
          - {version: 1.16.1, build: 138, download: 'paper-1.16.1-138.jar'}
          - {version: 1.16.2, build: 189, download: 'paper-1.16.2-189.jar'}
          - {version: 1.16.3, build: 253, download: 'paper-1.16.3-253.jar'}
          - {version: 1.16.4, build: 416, download: 'paper-1.16.4-416.jar'}
          - {version: 1.16.5, build: 794, download: 'paper-1.16.5-794.jar'}
          - {version: 1.17, build: 79, download: 'paper-1.17-79.jar'}
          - {version: 1.17.1, build: 411, download: 'paper-1.17.1-411.jar'}
          - {version: 1.18, build: 66, download: 'paper-1.18-66.jar'}
          - {version: 1.18.1, build: 216, download: 'paper-1.18.1-216.jar'}
          - {version: 1.18.2, build: 386, download: 'paper-1.18.2-386.jar'}
          - {version: 1.19, build: 31, download: 'paper-1.19-31.jar'}